## Checking missing values

In [1]:
import seaborn as sns

df = sns.load_dataset('titanic')
df

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


In [3]:
df['deck'].value_counts()

C    59
B    47
D    33
E    32
A    15
F    13
G     4
Name: deck, dtype: int64

In [4]:
df['deck'].value_counts(dropna=False)

NaN    688
C       59
B       47
D       33
E       32
A       15
F       13
G        4
Name: deck, dtype: int64

In [5]:
for col in df.columns:
    print(col, ":", df[col].isna().sum())

survived : 0
pclass : 0
sex : 0
age : 177
sibsp : 0
parch : 0
fare : 0
embarked : 2
class : 0
who : 0
adult_male : 0
deck : 688
embark_town : 2
alive : 0
alone : 0


## Fill missing values

In [6]:
df['age'].fillna(df['age'].median(), inplace=True)

In [7]:
df['embarked'].value_counts()

S    644
C    168
Q     77
Name: embarked, dtype: int64

In [8]:
df['embarked'].value_counts().idxmax()

'S'

In [9]:
df['embarked'].fillna(df['embarked'].value_counts().idxmax(), inplace=True)

In [10]:
df['embark_town'].value_counts()

Southampton    644
Cherbourg      168
Queenstown      77
Name: embark_town, dtype: int64

In [11]:
df['embark_town'].value_counts().idxmax()

'Southampton'

In [12]:
df['embark_town'].fillna(df['embark_town'].value_counts().idxmax(), inplace=True)

## Duplicate values

In [13]:
import pandas as pd

df = pd.DataFrame({'c1': ['a', 'a', 'b', 'a', 'b'],
                   'c2': [1, 1, 1, 2, 2], 
                   'c3': [1, 1, 2, 2, 2]})

df

c1  c2  c3
0  a   1   1
1  a   1   1
2  b   1   2
3  a   2   2
4  b   2   2

In [14]:
df.duplicated()

0    False
1     True
2    False
3    False
4    False
dtype: bool

In [15]:
df['c2'].duplicated()

0    False
1     True
2     True
3    False
4     True
Name: c2, dtype: bool

In [16]:
df2 = df.drop_duplicates()
df2

c1  c2  c3
0  a   1   1
2  b   1   2
3  a   2   2
4  b   2   2

In [17]:
df3 = df.drop_duplicates(subset=['c2', 'c3'])
df3

c1  c2  c3
0  a   1   1
2  b   1   2
3  a   2   2

## Unit conversion

In [18]:
import pandas as pd

df = pd.read_csv('data/auto-mpg.csv', header=None)
df.columns = ['mpg','cylinders','displacement','horsepower','weight','acceleration','model year','origin','name']
df.head()

mpg  cylinders  displacement horsepower  weight  acceleration  model year  \
0  18.0          8         307.0      130.0  3504.0          12.0          70   
1  15.0          8         350.0      165.0  3693.0          11.5          70   
2  18.0          8         318.0      150.0  3436.0          11.0          70   
3  16.0          8         304.0      150.0  3433.0          12.0          70   
4  17.0          8         302.0      140.0  3449.0          10.5          70   

   origin                       name  
0       1  chevrolet chevelle malibu  
1       1          buick skylark 320  
2       1         plymouth satellite  
3       1              amc rebel sst  
4       1                ford torino

In [19]:
mpg_to_kpl = 1.60934/3.78541
df['kpl'] = df['mpg'] * mpg_to_kpl
df['kpl'] = df['kpl'].round(2)
df.head()

mpg  cylinders  displacement horsepower  weight  acceleration  model year  \
0  18.0          8         307.0      130.0  3504.0          12.0          70   
1  15.0          8         350.0      165.0  3693.0          11.5          70   
2  18.0          8         318.0      150.0  3436.0          11.0          70   
3  16.0          8         304.0      150.0  3433.0          12.0          70   
4  17.0          8         302.0      140.0  3449.0          10.5          70   

   origin                       name   kpl  
0       1  chevrolet chevelle malibu  7.65  
1       1          buick skylark 320  6.38  
2       1         plymouth satellite  7.65  
3       1              amc rebel sst  6.80  
4       1                ford torino  7.23

## Datatype conversion

In [20]:
df.dtypes

mpg             float64
cylinders         int64
displacement    float64
horsepower       object
weight          float64
acceleration    float64
model year        int64
origin            int64
name             object
kpl             float64
dtype: object

In [21]:
df['horsepower'].unique()

array(['130.0', '165.0', '150.0', '140.0', '198.0', '220.0', '215.0',
       '225.0', '190.0', '170.0', '160.0', '95.00', '97.00', '85.00',
       '88.00', '46.00', '87.00', '90.00', '113.0', '200.0', '210.0',
       '193.0', '?', '100.0', '105.0', '175.0', '153.0', '180.0', '110.0',
       '72.00', '86.00', '70.00', '76.00', '65.00', '69.00', '60.00',
       '80.00', '54.00', '208.0', '155.0', '112.0', '92.00', '145.0',
       '137.0', '158.0', '167.0', '94.00', '107.0', '230.0', '49.00',
       '75.00', '91.00', '122.0', '67.00', '83.00', '78.00', '52.00',
       '61.00', '93.00', '148.0', '129.0', '96.00', '71.00', '98.00',
       '115.0', '53.00', '81.00', '79.00', '120.0', '152.0', '102.0',
       '108.0', '68.00', '58.00', '149.0', '89.00', '63.00', '48.00',
       '66.00', '139.0', '103.0', '125.0', '133.0', '138.0', '135.0',
       '142.0', '77.00', '62.00', '132.0', '84.00', '64.00', '74.00',
       '116.0', '82.00'], dtype=object)

In [22]:
import numpy as np
df['horsepower'].replace('?', np.nan, inplace=True)
df.dropna(subset=['horsepower'], axis=0, inplace=True)
df['horsepower'] = df['horsepower'].astype('float')
df['horsepower'].dtype

dtype('float64')

In [23]:
df['origin'].unique()

array([1, 3, 2], dtype=int64)

In [24]:
df['origin'].replace({1: 'USA', 2:'EU', 3:'JPN'}, inplace=True)
df['origin'].unique()

array(['USA', 'JPN', 'EU'], dtype=object)

In [25]:
df['origin'] = df['origin'].astype('category')
df['origin'].unique()

['USA', 'JPN', 'EU']
Categories (3, object): ['EU', 'JPN', 'USA']

In [26]:
df['model year'].dtype

dtype('int64')

In [27]:
df['model year'] = df['model year'].astype('category')
df['model year'].unique()

[70, 71, 72, 73, 74, ..., 78, 79, 80, 81, 82]
Length: 13
Categories (13, int64): [70, 71, 72, 73, ..., 79, 80, 81, 82]

In [28]:
## Binning
np.histogram(df['horsepower'], bins=3)

(array([257, 103,  32], dtype=int64),
 array([ 46.        , 107.33333333, 168.66666667, 230.        ]))

In [29]:
count, bin_dividers = np.histogram(df['horsepower'], bins=3)

bin_names = ['low', 'medium', 'high']

df['hp_bin'] = pd.cut(x=df['horsepower'], bins=bin_dividers, labels=bin_names, include_lowest=True)

In [30]:
df[['horsepower', 'hp_bin']].head(15)

horsepower  hp_bin
0        130.0  medium
1        165.0  medium
2        150.0  medium
3        150.0  medium
4        140.0  medium
5        198.0    high
6        220.0    high
7        215.0    high
8        225.0    high
9        190.0    high
10       170.0    high
11       160.0  medium
12       150.0  medium
13       225.0    high
14        95.0     low

## Get dummies

In [31]:
hp_dummies = pd.get_dummies(df['hp_bin'])
hp_dummies.head(15)

low  medium  high
0     0       1     0
1     0       1     0
2     0       1     0
3     0       1     0
4     0       1     0
5     0       0     1
6     0       0     1
7     0       0     1
8     0       0     1
9     0       0     1
10    0       0     1
11    0       1     0
12    0       1     0
13    0       0     1
14    1       0     0

In [32]:
# using sklearn

# import sklearn.preprocessing
from sklearn import preprocessing

# encoder
label_encoder = preprocessing.LabelEncoder()
onehot_encoder = preprocessing.OneHotEncoder()

# label encode (str category -> int category)
onehot_labeled = label_encoder.fit_transform(df['hp_bin'])
print(onehot_labeled[:15])

# 1D -> 2D
onehot_reshaped = onehot_labeled.reshape(len(onehot_labeled), 1)
print(onehot_reshaped[:15])

# onehot encode (sparse matrix)
onehot_fitted = onehot_encoder.fit_transform(onehot_reshaped)
print(onehot_fitted[:15])

[2 2 2 2 2 0 0 0 0 0 0 2 2 0 1]
[[2]
 [2]
 [2]
 [2]
 [2]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [2]
 [2]
 [0]
 [1]]
  (0, 2)	1.0
  (1, 2)	1.0
  (2, 2)	1.0
  (3, 2)	1.0
  (4, 2)	1.0
  (5, 0)	1.0
  (6, 0)	1.0
  (7, 0)	1.0
  (8, 0)	1.0
  (9, 0)	1.0
  (10, 0)	1.0
  (11, 2)	1.0
  (12, 2)	1.0
  (13, 0)	1.0
  (14, 1)	1.0


## Normalize max

In [33]:
df['horsepower'].describe()

count    392.000000
mean     104.469388
std       38.491160
min       46.000000
25%       75.000000
50%       93.500000
75%      126.000000
max      230.000000
Name: horsepower, dtype: float64

In [34]:
df['hp_normal_1'] = df['horsepower'] / df['horsepower'].max()
df['hp_normal_1']

0      0.565217
1      0.717391
2      0.652174
3      0.652174
4      0.608696
         ...   
393    0.373913
394    0.226087
395    0.365217
396    0.343478
397    0.356522
Name: hp_normal_1, Length: 392, dtype: float64

In [35]:
df['hp_normal_1'].describe()

count    392.000000
mean       0.454215
std        0.167353
min        0.200000
25%        0.326087
50%        0.406522
75%        0.547826
max        1.000000
Name: hp_normal_1, dtype: float64

## Normalize min max

In [36]:
def min_max_normalize(x):
    return (x - x.min()) / (x.max() - x.min())

In [37]:
df['hp_normal_2'] = min_max_normalize(df['horsepower'])
df['hp_normal_2']

0      0.456522
1      0.646739
2      0.565217
3      0.565217
4      0.510870
         ...   
393    0.217391
394    0.032609
395    0.206522
396    0.179348
397    0.195652
Name: hp_normal_2, Length: 392, dtype: float64

In [38]:
df['hp_normal_2'].describe()

count    392.000000
mean       0.317768
std        0.209191
min        0.000000
25%        0.157609
50%        0.258152
75%        0.434783
max        1.000000
Name: hp_normal_2, dtype: float64

## Time series

In [39]:
df = pd.read_csv('data/stock-data.csv')
df.head()

Date  Close  Start   High    Low  Volume
0  2018-07-02  10100  10850  10900  10000  137977
1  2018-06-29  10700  10550  10900   9990  170253
2  2018-06-28  10400  10900  10950  10150  155769
3  2018-06-27  10900  10800  11050  10500  133548
4  2018-06-26  10800  10900  11000  10700   63039

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Date    20 non-null     object
 1   Close   20 non-null     int64 
 2   Start   20 non-null     int64 
 3   High    20 non-null     int64 
 4   Low     20 non-null     int64 
 5   Volume  20 non-null     int64 
dtypes: int64(5), object(1)
memory usage: 1.1+ KB


In [41]:
df['New_Date'] = pd.to_datetime(df['Date'])
df.head()

Date  Close  Start   High    Low  Volume   New_Date
0  2018-07-02  10100  10850  10900  10000  137977 2018-07-02
1  2018-06-29  10700  10550  10900   9990  170253 2018-06-29
2  2018-06-28  10400  10900  10950  10150  155769 2018-06-28
3  2018-06-27  10900  10800  11050  10500  133548 2018-06-27
4  2018-06-26  10800  10900  11000  10700   63039 2018-06-26

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype         
---  ------    --------------  -----         
 0   Date      20 non-null     object        
 1   Close     20 non-null     int64         
 2   Start     20 non-null     int64         
 3   High      20 non-null     int64         
 4   Low       20 non-null     int64         
 5   Volume    20 non-null     int64         
 6   New_Date  20 non-null     datetime64[ns]
dtypes: datetime64[ns](1), int64(5), object(1)
memory usage: 1.2+ KB


In [43]:
df.set_index('New_Date', inplace=True)
df.drop('Date', axis=1, inplace=True)
df.head()

Close  Start   High    Low  Volume
New_Date                                      
2018-07-02  10100  10850  10900  10000  137977
2018-06-29  10700  10550  10900   9990  170253
2018-06-28  10400  10900  10950  10150  155769
2018-06-27  10900  10800  11050  10500  133548
2018-06-26  10800  10900  11000  10700   63039

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 20 entries, 2018-07-02 to 2018-06-01
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Close   20 non-null     int64
 1   Start   20 non-null     int64
 2   High    20 non-null     int64
 3   Low     20 non-null     int64
 4   Volume  20 non-null     int64
dtypes: int64(5)
memory usage: 960.0 bytes


## Timestamps -> periods

In [45]:
dates = ['2019-01-01', '2020-03-01', '2021-06-01']

# to timestamp
ts_dates = pd.to_datetime(dates)
ts_dates

DatetimeIndex(['2019-01-01', '2020-03-01', '2021-06-01'], dtype='datetime64[ns]', freq=None)

In [46]:
# to period
pr_day = ts_dates.to_period(freq='D')
print(pr_day)

pr_month = ts_dates.to_period(freq='M')
print(pr_month)

pr_year = ts_dates.to_period(freq='A')
print(pr_year)

# freq
# D : day
# W : week
# M : month
# MS : month begin
# Q : quarter
# QS : quarter begin
# A : year end
# AS : year begin
# B : business day
# H : hour
# T : minute
# S : second
# L : millisecond (1/1_000s)
# U : microsecond (1/1_000_000s)
# N : nanosecond (1/1_000_000_000s)

PeriodIndex(['2019-01-01', '2020-03-01', '2021-06-01'], dtype='period[D]')
PeriodIndex(['2019-01', '2020-03', '2021-06'], dtype='period[M]')
PeriodIndex(['2019', '2020', '2021'], dtype='period[A-DEC]')


## Date range

In [47]:
ts_ms = pd.date_range(start='2019-01-01', 
                      end=None, 
                      periods=6, 
                      freq='MS', 
                      tz='Asia/Seoul')
ts_ms

DatetimeIndex(['2019-01-01 00:00:00+09:00', '2019-02-01 00:00:00+09:00',
               '2019-03-01 00:00:00+09:00', '2019-04-01 00:00:00+09:00',
               '2019-05-01 00:00:00+09:00', '2019-06-01 00:00:00+09:00'],
              dtype='datetime64[ns, Asia/Seoul]', freq='MS')

In [48]:
ts_me = pd.date_range(start='2019-01-01', 
                      end=None, 
                      periods=6, 
                      freq='M', 
                      tz='Asia/Seoul')
ts_me

DatetimeIndex(['2019-01-31 00:00:00+09:00', '2019-02-28 00:00:00+09:00',
               '2019-03-31 00:00:00+09:00', '2019-04-30 00:00:00+09:00',
               '2019-05-31 00:00:00+09:00', '2019-06-30 00:00:00+09:00'],
              dtype='datetime64[ns, Asia/Seoul]', freq='M')

In [49]:
ts_3m = pd.date_range(start='2019-01-01', 
                      end=None, 
                      periods=6, 
                      freq='3M', 
                      tz='Asia/Seoul')
ts_3m

DatetimeIndex(['2019-01-31 00:00:00+09:00', '2019-04-30 00:00:00+09:00',
               '2019-07-31 00:00:00+09:00', '2019-10-31 00:00:00+09:00',
               '2020-01-31 00:00:00+09:00', '2020-04-30 00:00:00+09:00'],
              dtype='datetime64[ns, Asia/Seoul]', freq='3M')

## Period range

In [50]:
pr_m = pd.period_range(start='2019-01-01', 
                       end=None, 
                       periods=3, 
                       freq='M')
pr_m

PeriodIndex(['2019-01', '2019-02', '2019-03'], dtype='period[M]')

In [51]:
pr_h = pd.period_range(start='2019-01-01', 
                       end=None, 
                       periods=3, 
                       freq='H')
pr_h

PeriodIndex(['2019-01-01 00:00', '2019-01-01 01:00', '2019-01-01 02:00'], dtype='period[H]')

In [52]:
pr_2h = pd.period_range(start='2019-01-01', 
                       end=None, 
                       periods=3, 
                       freq='2H')
pr_2h

PeriodIndex(['2019-01-01 00:00', '2019-01-01 02:00', '2019-01-01 04:00'], dtype='period[2H]')

## Datetime format

In [53]:
df = pd.read_csv('data/stock-data.csv')
df['new_date'] = pd.to_datetime(df['Date'])
df.head()

Date  Close  Start   High    Low  Volume   new_date
0  2018-07-02  10100  10850  10900  10000  137977 2018-07-02
1  2018-06-29  10700  10550  10900   9990  170253 2018-06-29
2  2018-06-28  10400  10900  10950  10150  155769 2018-06-28
3  2018-06-27  10900  10800  11050  10500  133548 2018-06-27
4  2018-06-26  10800  10900  11000  10700   63039 2018-06-26

In [54]:
df['year'] = df['new_date'].dt.year
df['month'] = df['new_date'].dt.month
df['day'] = df['new_date'].dt.day
df.head()

Date  Close  Start   High    Low  Volume   new_date  year  month  day
0  2018-07-02  10100  10850  10900  10000  137977 2018-07-02  2018      7    2
1  2018-06-29  10700  10550  10900   9990  170253 2018-06-29  2018      6   29
2  2018-06-28  10400  10900  10950  10150  155769 2018-06-28  2018      6   28
3  2018-06-27  10900  10800  11050  10500  133548 2018-06-27  2018      6   27
4  2018-06-26  10800  10900  11000  10700   63039 2018-06-26  2018      6   26

In [55]:
df['date_year'] = df['new_date'].dt.to_period(freq='A')
df['date_month'] = df['new_date'].dt.to_period(freq='M')
df.head()

Date  Close  Start   High    Low  Volume   new_date  year  month  \
0  2018-07-02  10100  10850  10900  10000  137977 2018-07-02  2018      7   
1  2018-06-29  10700  10550  10900   9990  170253 2018-06-29  2018      6   
2  2018-06-28  10400  10900  10950  10150  155769 2018-06-28  2018      6   
3  2018-06-27  10900  10800  11050  10500  133548 2018-06-27  2018      6   
4  2018-06-26  10800  10900  11000  10700   63039 2018-06-26  2018      6   

   day date_year date_month  
0    2      2018    2018-07  
1   29      2018    2018-06  
2   28      2018    2018-06  
3   27      2018    2018-06  
4   26      2018    2018-06

## Datetime indexing

In [56]:
df = pd.read_csv('data/stock-data.csv')
df['new_date'] = pd.to_datetime(df['Date'])
df.set_index('new_date', inplace=True)
df.head()

Date  Close  Start   High    Low  Volume
new_date                                                  
2018-07-02  2018-07-02  10100  10850  10900  10000  137977
2018-06-29  2018-06-29  10700  10550  10900   9990  170253
2018-06-28  2018-06-28  10400  10900  10950  10150  155769
2018-06-27  2018-06-27  10900  10800  11050  10500  133548
2018-06-26  2018-06-26  10800  10900  11000  10700   63039

In [57]:
df.index

DatetimeIndex(['2018-07-02', '2018-06-29', '2018-06-28', '2018-06-27',
               '2018-06-26', '2018-06-25', '2018-06-22', '2018-06-21',
               '2018-06-20', '2018-06-19', '2018-06-18', '2018-06-15',
               '2018-06-14', '2018-06-12', '2018-06-11', '2018-06-08',
               '2018-06-07', '2018-06-05', '2018-06-04', '2018-06-01'],
              dtype='datetime64[ns]', name='new_date', freq=None)

In [58]:
df.loc['2018']

Date  Close  Start   High    Low  Volume
new_date                                                  
2018-07-02  2018-07-02  10100  10850  10900  10000  137977
2018-06-29  2018-06-29  10700  10550  10900   9990  170253
2018-06-28  2018-06-28  10400  10900  10950  10150  155769
2018-06-27  2018-06-27  10900  10800  11050  10500  133548
2018-06-26  2018-06-26  10800  10900  11000  10700   63039
2018-06-25  2018-06-25  11150  11400  11450  11000   55519
2018-06-22  2018-06-22  11300  11250  11450  10750  134805
2018-06-21  2018-06-21  11200  11350  11750  11200  133002
2018-06-20  2018-06-20  11550  11200  11600  10900  308596
2018-06-19  2018-06-19  11300  11850  11950  11300  180656
2018-06-18  2018-06-18  12000  13400  13400  12000  309787
2018-06-15  2018-06-15  13400  13600  13600  12900  201376
2018-06-14  2018-06-14  13450  13200  13700  13150  347451
2018-06-12  2018-06-12  13200  12200  13300  12050  558148
2018-06-11  2018-06-11  11950  12000  12250  11950   62293
2018-06-08  2018-06-08  11950  11950  12200  11800   59258
2018-06-07  2018-06-07  11950  12200  12300  11900   49088
2018-06-05  2018-06-05  12150  11800  12250  11800   42485
2018-06-04  2018-06-04  11900  11900  12200  11700   25171
2018-06-01  2018-06-01  11900  11800  12100  11750   32062

In [59]:
df.loc['2018-07']

Date  Close  Start   High    Low  Volume
new_date                                                  
2018-07-02  2018-07-02  10100  10850  10900  10000  137977

In [60]:
df.loc['2018-07', 'Start':'High']

Start   High
new_date                
2018-07-02  10850  10900

In [61]:
df.loc['2018-07-02']

Date  Close  Start   High    Low  Volume
new_date                                                  
2018-07-02  2018-07-02  10100  10850  10900  10000  137977

In [62]:
df.loc['2018-06-25':'2018-06-21'] # deprecated

Empty DataFrame
Columns: [Date, Close, Start, High, Low, Volume]
Index: []

In [63]:
df.loc[['2018-06-25', '2018-06-22', '2018-06-21'], ]

Date  Close  Start   High    Low  Volume
new_date                                                  
2018-06-25  2018-06-25  11150  11400  11450  11000   55519
2018-06-22  2018-06-22  11300  11250  11450  10750  134805
2018-06-21  2018-06-21  11200  11350  11750  11200  133002

In [64]:
today = pd.to_datetime('2022-01-05')
df['time_delta'] = today - df.index
df.head()

Date  Close  Start   High    Low  Volume time_delta
new_date                                                             
2018-07-02  2018-07-02  10100  10850  10900  10000  137977  1283 days
2018-06-29  2018-06-29  10700  10550  10900   9990  170253  1286 days
2018-06-28  2018-06-28  10400  10900  10950  10150  155769  1287 days
2018-06-27  2018-06-27  10900  10800  11050  10500  133548  1288 days
2018-06-26  2018-06-26  10800  10900  11000  10700   63039  1289 days

In [65]:
df.reset_index(inplace=True)
df.set_index('time_delta', inplace=True)
df.head()

new_date        Date  Close  Start   High    Low  Volume
time_delta                                                           
1283 days  2018-07-02  2018-07-02  10100  10850  10900  10000  137977
1286 days  2018-06-29  2018-06-29  10700  10550  10900   9990  170253
1287 days  2018-06-28  2018-06-28  10400  10900  10950  10150  155769
1288 days  2018-06-27  2018-06-27  10900  10800  11050  10500  133548
1289 days  2018-06-26  2018-06-26  10800  10900  11000  10700   63039

In [66]:
df['1286 days':'1289 days']

new_date        Date  Close  Start   High    Low  Volume
time_delta                                                           
1286 days  2018-06-29  2018-06-29  10700  10550  10900   9990  170253
1287 days  2018-06-28  2018-06-28  10400  10900  10950  10150  155769
1288 days  2018-06-27  2018-06-27  10900  10800  11050  10500  133548
1289 days  2018-06-26  2018-06-26  10800  10900  11000  10700   63039